import verifyToken from "../backend/verifyToken";
import cookie from "cookie";
import Head from "next/head";

export default function Dashboard() {
	return (
		<>
			<Head>
				<title>Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>dashboard</div>;
		</>
	);
}

export async function getServerSideProps(context) {
	if (!context.req.headers.cookie)
		return {
			redirect: {
				permanent: false,
				destination: "/giris",
			},
			props: {},
		};

	const parsedCookie = cookie.parse(context.req.headers.cookie);
	const userData = await verifyToken(parsedCookie.token);
	console.log(userData);
	if (userData.is_hr === false)
		return {
			redirect: {
				permanent: false,
				destination: "/",
			},
			props: {},
		};

	return {
		props: {}, // will be passed to the page component as props
	};
}
