import Head from "next/head";
import verifyToken from "../backend/verifyToken";
import cookie from "cookie";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Anasayfa</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="text-red-500">homepage</div>
		</div>
	);
}

export async function getServerSideProps(context) {
	if (!context.req.headers.cookie)
		return {
			redirect: {
				permanent: false,
				destination: "/giris",
			},
			props: {},
		};

	const parsedCookie = cookie.parse(context.req.headers.cookie);
	const userData = await verifyToken(parsedCookie.token);
	console.log(userData);
	if (userData.is_manager === false)
		return {
			redirect: {
				permanent: false,
				destination: "/yetkisiz-islem",
			},
			props: {},
		};

	return {
		props: {},
	};
}
